# Generated by Django 2.1.4 on 2018-12-22 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipality',
            old_name='name',
            new_name='label',
        ),
    ]
