# Generated by Django 2.1.4 on 2018-12-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181222_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitedmunicipality',
            old_name='badge',
            new_name='municipality',
        ),
    ]
