# Generated by Django 2.1.4 on 2018-12-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181222_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='flag_image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
