# Generated by Django 2.1.4 on 2018-12-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181222_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='multi_polygon_str',
            field=models.CharField(max_length=300000, null=True),
        ),
    ]
