# Generated by Django 2.1.4 on 2018-12-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_municipality_multi_polygon_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='multi_polygon_str',
            field=models.CharField(max_length=400000, null=True),
        ),
    ]
