# Generated by Django 2.1.4 on 2019-01-17 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_municipalitylist_municipalitylistmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityListTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=500)),
            ],
        ),
    ]
