# Generated by Django 2.1.4 on 2019-01-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_municipalitylisttypes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MunicipalityListTypes',
            new_name='MunicipalityListType',
        ),
    ]
