# Generated by Django 2.1.4 on 2019-01-17 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_municipalitylist_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipalitylist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MunicipalityListType'),
        ),
    ]
