# Generated by Django 2.1.4 on 2019-01-17 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190117_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidenceMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=200)),
                ('city_code', models.CharField(max_length=6)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Municipality')),
            ],
        ),
        migrations.AlterField(
            model_name='municipalitylist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 12, 8, 11, 164872, tzinfo=utc), verbose_name='date published'),
        ),
    ]
