# Generated by Django 2.1.4 on 2019-01-17 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190117_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipalitylist',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='municipalitylist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 13, 49, 21, 316721, tzinfo=utc), verbose_name='date published'),
        ),
    ]
